{application,em_filter,
             [{description,"Agent connectivity for Emergence system."},
              {vsn,"1.2.4"},
              {registered,[em_filter_sup]},
              {mod,{em_filter_app,[]}},
              {applications,[kernel,stdlib,gun]},
              {env,[]},
              {modules,[em_filter,em_filter_app,em_filter_server,
                        em_filter_sup]},
              {licenses,["Apache-2.0"]},
              {links,[{"GitHub",
                       "https://github.com/EmergenceSystem/em_filter"}]}]}.
